### PR TITLE
Moving to neuromV2

### PR DESCRIPTION
**Pull request by tomdele**

### CODE REVIEW

**Review by asanin-epfl — APPROVED** [review]
so, do we have neurom as dependency only because of tests?

**Comment by tomdele** [comment]
No we have the reader also in the morph helper and the get which returns a neurom morphology

**Comment by tomdele** [comment]
the api did not change so I did not need to change the piece of code in the morphHelper. And I think this `get` function is useful due to the transformation matrix that is not 100% trivial we apply on the morphology.

**Comment by asanin-epfl** [comment]
ah, ok. Thank you for clarifying!

**Pull request merged**
