### PR TITLE
Fix documentation build with new Sphinx

### PR DESCRIPTION
**Pull request by haleepfl**
New sphinx appears to have an issue with the "name" template
variable. To solve, we remove our custom template which will
also reduce the risk of future breakages. This will however
add the fully qualified submodule name in the toctree.

### CODE REVIEW

**Comment by tomdele** [comment]
I must say I am not sure what I review here ...

**Comment by tomdele** [comment]
Can you give me more info ?

**Comment by haleepfl** [comment]
SNAP documentation builds are currently failing: https://readthedocs.org/projects/bluebrainsnap/builds/11240661/

This seems to be caused by a new release of Sphinx being incompatible with our custom autosummary template. To simplify things, I've remove the custom template (at the expense of slightly longer tables of contents) which fixes the build issue.

**Comment by tomdele** [comment]
Ok, thanks for the clarification. 
So we gonna have the attributes and the raise also ?

**Comment by haleepfl** [comment]
> Ok, thanks for the clarification.
> So we gonna have the attributes and the raise also ?

Yes, we should see all module members.

**Pull request merged**
