### PR TITLE
Improve circuit validation for virtual nodes

### PR DESCRIPTION
**Pull request by asanin-epfl**
- Change return type of circuit validation from list to set
- Check for 'components' only for biophysical nodes

### CODE REVIEW

**Comment by tomdele** [comment]
I will let @joni-herttuainen do the review first and I will check afterwards. 
@joni-herttuainen, this module is used to validate sonata circuit format. It does quite a lot of checks and returns the errors at the end. The ground truth for this is the [sonata specs page ](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md)

**Comment by joni-herttuainen** [comment]
> I will let @joni-herttuainen do the review first and I will check afterwards.
> @joni-herttuainen, this module is used to validate sonata circuit format. It does quite a lot of checks and returns the errors at the end. The ground truth for this is the [sonata specs page](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md)

I just started going through this, thanks for the link 👍

**Comment by tomdele** [comment]
Thx @joni-herttuainen, no worries if you don t get trough all the specs this is massive an confusing enough. Therefore, this is important for you to know the format quite well in the future and I think snap PR is a great starting point. If there is something confusing ask me or @asanin-epfl.

**Comment by asanin-epfl** [comment]
Tom thanks for intro! I completely forgot to do it.

**Pull request merged**
