### PR TITLE
Fix deprecation warnings

### LINKED ISSUE #89: Deprecation warning collections
Just letting you know that my tests get a deprecation warning:
bluepysnap/nodes.py:421: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working

### PR DESCRIPTION
**Pull request by tirkarthi**
* Import ABC from collections.abc in Python 3. Fixes #89 
* Fix deprecation warning regarding invalid escape sequences.

### CODE REVIEW

**Comment by tirkarthi** [comment]
The CI seems to fail due to test coverage being less than 100% . I guess the branch of Python 2 code won't be run which might be affecting this.

**Comment by mgeplf** [comment]
We will look at this next week, thanks for the contribution.

**Comment by tomdele** [comment]
Hello, 
thanks @tirkarthi for the contribution. This is really appreciated ! 
Indeed the py27 try/except branch cannot be tested during the py36 testing run ... I never found a proper way of testing this for widely spread libraries during the tests.
Ex here, we cannot do a simple: 
```
def test_import():
    with mock.patch.dict(sys.modules, {'collections.abc': None})
        ...
```
Because `collections` is used also by numpy or pathlib which are imported during snap module imports.  

Do you have any idea on how to test this even in python3 ? 
if not we will need to  `# pragma: no cover`.

**Comment by tomdele** [comment]
I will close this PR which is now obsolete with the python2 support removal from #109. I included the changes from this PR to the #109 one.
Thank you @tirkarthi for the contribution.

**Pull request closed without merging**
