### PR TITLE
Added kgforge.py (KGForge wrapper for Simulation and Circuit)

### PR DESCRIPTION
**Pull request by joni-herttuainen**

### CODE REVIEW

**Comment by tomdele** [comment]
Should I take actions on this ?

**Comment by joni-herttuainen** [comment]
This is the same commit you already reviewed last week. I am currently working on this and adding new stuff so maybe it would be better to add my changes to the side branch, so it is easier to keep track (and discuss + review) of what is changing when I make a new commit.

**Comment by tomdele** [comment]
You should be able to do it yourself, no ?

**Comment by tomdele** [comment]
If not, you need to ask for the proper access rights

**Comment by joni-herttuainen** [comment]
Yeah, I'll do it.

**Pull request merged**
