### PR TITLE
fix report query for empty arrays or tuple

### PR DESCRIPTION
**Pull request by tomdele**
fix for report .get function with empty tuple and array

### CODE REVIEW

**Comment by asanin-epfl** [comment]
Should we check just for an instance of iterable then?

**Comment by tomdele** [comment]
No, because dicts are also iterables and the behavior of `nodes.ids(group={})` is: return all node_ids. So I wanted to keep the same behavior here. 
I never found a proper function included in a widespread lib to check this kind of stuffs... So if you have something to do that in a clean way I take it !

**Comment by tomdele** [comment]
simple question but not so simple answer :smile:

**Comment by tomdele** [comment]
thank you guys

**Pull request merged**
